# Generated by Django 2.0 on 2018-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0003_feedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'feedback', 'verbose_name_plural': 'feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='ack',
            field=models.BooleanField(default=False, verbose_name='Acknowledgement'),
        ),
    ]
